CREATE DATABASE ATIVIDADE;

--SEXO = {CODSEXO, NOMESEXO}
CREATE TABLE SEXO(
	CODSEXO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMESEXO VARCHAR(9) NOT NULL UNIQUE
);
--RUA = {CODRUA, NOMERUA}
CREATE TABLE RUA(
	CODRUA INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMERUA VARCHAR(80) NOT NULL UNIQUE
);
--BAIRRO = {CODBAIRRO, NOMEBAIRRO}
CREATE TABLE BAIRRO(
	CODBAIRRO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEBAIRRO VARCHAR(80) NOT NULL UNIQUE
);
--CEP = {CODCEP, NUMEROCEP}
CREATE TABLE CEP(
	CODCEP INTEGER IDENTITY(1,1) PRIMARY KEY,
	NUMEROCEP CHAR(9) NOT NULL UNIQUE
);
--UF = {CODUF, NOMEUF, SIGLA}
CREATE TABLE UF(
	CODUF INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEUF VARCHAR(80) NOT NULL UNIQUE,
	SIGLA CHAR(2) NOT NULL UNIQUE
);
-- CIDADE = {CODCIDADE, NOMECIDADE, CODUF}
CREATE TABLE CIDADE(
	CODCIDADE INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMECIDADE VARCHAR(80) NOT NULL UNIQUE,
	CODUF_FK INTEGER REFERENCES UF(CODUF) ON DELETE CASCADE ON UPDATE CASCADE
);
-- TRABALHO = {CODTRABALHO, NOMETRABALHO}
CREATE TABLE TRABALHO(
	CODTRABALHO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMETRABALHO VARCHAR(80) NOT NULL
);
--CLIENTE = {CODCLIENTE, NOMECLIENTE, FOTO, DATANASC, CODSEXO, CODRUA,
--CODBAIRRO, CODCEP, CODCIDADE, SALARIO, CODTRABALHO, NUMEROCASA}
CREATE TABLE CLIENTE(
	CODCLIENTE INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMECLIENTE VARCHAR(80) NOT NULL,
	FOTO VARBINARY(MAX),
	DATANASC VARCHAR(80) NOT NULL,
	CODSEXO_FK INTEGER REFERENCES SEXO(CODSEXO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODRUA_FK INTEGER REFERENCES RUA(CODRUA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODBAIRRO_FK INTEGER REFERENCES BAIRRO(CODBAIRRO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCEP_FK INTEGER REFERENCES CEP(CODCEP) ON DELETE CASCADE ON UPDATE CASCADE,
	SALARIO NUMERIC(10,2) NOT NULL,
	CODTRABALHO_FK INTEGER REFERENCES TRABALHO(CODTRABALHO) ON DELETE CASCADE ON UPDATE CASCADE,
	NUMEROCASA VARCHAR(10) NOT NULL
);
--OPERADORA = {CODPERADORA, NOMEOPERADORA}
CREATE TABLE OPERADORA(
	CODOPERADORA INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEOPERADORA VARCHAR(80) NOT NULL UNIQUE
);
--TELEFONE = {CODTELEFONE, NUMERO, CODOPERADORA}
CREATE TABLE TELEFONE(
	CODTELEFONE INTEGER IDENTITY(1,1) PRIMARY KEY,
	NUMERO CHAR(9) NOT NULL UNIQUE,
	CODOPERADORA_FK INTEGER REFERENCES OPERADORA(CODOPERADORA) ON DELETE CASCADE ON UPDATE CASCADE,
);
--ITENSTELCLIENTE = {CODTELEFONE, CODCLIENTE}
CREATE TABLE ITENSTELCLIENTE(
	CODTELEFONE_FK INTEGER REFERENCES TELEFONE(CODTELEFONE) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCLIENTE_FK INTEGER REFERENCES CLIENTE(CODCLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
);
--ITENSTELEFONETRABALHO = {CODTRABALHO, CODTELEFONE}
CREATE TABLE ITENSTELEFONETRABALHO(
	CODTRABALHO_FK INTEGER REFERENCES TRABALHO(CODTRABALHO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODTELEFONE_FK INTEGER REFERENCES TELEFONE(CODTELEFONE) ON DELETE CASCADE ON UPDATE CASCADE
);
--FUNCAO = {CODFUNCAO, NOMEFUNCAO}
CREATE TABLE FUNCAO(
	CODFUNCAO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEFUNCAO VARCHAR(80) NOT NULL UNIQUE
);
--LOJA = {CODLOJA, NOMELOJA, CNPJ, NOMEFANTASIA, RAZAOSOCIAL}
CREATE TABLE LOJA(
	CODLOJA INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMELOJA VARCHAR(80) NOT NULL,
	CNPJ CHAR (14) NOT NULL UNIQUE,
	NOMEFANTASIA VARCHAR(80) NOT NULL,
	RAZAOSOCIAL VARCHAR(80) NOT NULL UNIQUE
);
--ITENSTELEFONELOJA={CODLOJA, CODTELEFONE}
CREATE TABLE ITENSTELEFONELOJA(
	CODLOJA_FK INTEGER REFERENCES LOJA(CODLOJA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODTELEFONE_FK INTEGER REFERENCES TELEFONE(CODTELEFONE) ON DELETE CASCADE ON UPDATE CASCADE
);
--FUNCIONARIOS = {CODFUNCIONARIO, NOMEFUNCIONARIO, NUMEROCASA,
--CODRUA, CODBAIRRO, CODCEP, CODCIDADE, CODFUNCAO, SALARIO, CODLOJA}
CREATE TABLE FUNCIONARIOS(
	CODFUNCIONARIOS INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEFUNCIONARIO VARCHAR(80) NOT NULL,
	NUMEROCASA VARCHAR(10) NOT NULL,
	CODRUA_FK INTEGER REFERENCES RUA(CODRUA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODBAIRRO_FK INTEGER REFERENCES BAIRRO(CODBAIRRO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCEP_FK INTEGER REFERENCES CEP(CODCEP) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCIDADE_FK INTEGER REFERENCES CIDADE(CODCIDADE) ON DELETE CASCADE ON UPDATE CASCADE,
	CODFUNCAO_FK INTEGER REFERENCES FUNCAO(CODFUNCAO) ON DELETE CASCADE ON UPDATE CASCADE,
	SALARIOFUNCIONARIO NUMERIC(10,2) NOT NULL,
	CODLOJA_FK INTEGER REFERENCES LOJA(CODLOJA) ON DELETE CASCADE ON UPDATE CASCADE
);
--ITENSTELEFONEFUNCIONARIO = {CODFUNCIONARIO, CODTELEFONE}
CREATE TABLE ITENSTELEFONEFUNCIONARIO(
	CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(CODFUNCIONARIOS) ON DELETE CASCADE ON UPDATE CASCADE,
	CODTELEFONE_FK INTEGER REFERENCES TELEFONE(CODTELEFONE) ON DELETE CASCADE ON UPDATE CASCADE
);
--LOGIN = {CODLOGIN, USUARIO, SENHA, CODFUNCIONARIO}
CREATE TABLE LOGIN(
	CODLOGIN INTEGER IDENTITY(1,1) PRIMARY KEY,
	USUARIO VARCHAR(80) NOT NULL UNIQUE,
	SENHA CHAR(40) NOT NULL,
	CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(CODFUNCIONARIOS) ON DELETE CASCADE ON UPDATE CASCADE
);
--CONTROLELOGSISTEMA = {CODCONTROLE, CODLOGIN, DATA, HORA}
CREATE TABLE CONTROLELOGSISTEMA(
	CODCONTROLE INTEGER IDENTITY(1,1) PRIMARY KEY,
	CODLOGIN_FK INTEGER REFERENCES LOGIN(CODLOGIN) ON DELETE CASCADE ON UPDATE CASCADE,
	DATA DATE NOT NULL,
	HORA TIME NOT NULL
);
-- ACESSO = {CODACESSO, NOMEACESSO}
CREATE TABLE ACESSO(
	CODACESSO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEACESSO VARCHAR(80) NOT NULL UNIQUE
);
--ITENSACESSOLOGIN = {CODACESSO, CODLOGIN}
CREATE TABLE ITENSACESSOLOGIN(
	CODACESSO_FK INTEGER REFERENCES ACESSO(CODACESSO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODLOGIN_FK INTEGER REFERENCES LOGIN(CODLOGIN) ON DELETE CASCADE ON UPDATE CASCADE
);
--MARCA={CODMARCA, NOMEMARCA}
CREATE TABLE MARCA(
	CODMARCA INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEMARCA VARCHAR(80) NOT NULL UNIQUE
);
--TIPO={CODTIPO, NOMETIPO}
	CREATE TABLE TIPO(
	CODTIPO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMETIPO VARCHAR(80) NOT NULL UNIQUE
);
--PRODUTO = {CODPRODUTO, NOMEPRODUTO, QUANTIDADE, VALOR, CODMARCA,
--CODTIPO }
CREATE TABLE PRODUTO(
	CODPRODUTO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEPRODUTO VARCHAR(80) UNIQUE,
	QUANTIDADE NUMERIC(10,2) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	CODMARCA_FK INTEGER REFERENCES MARCA(CODMARCA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODTIPO_FK INTEGER REFERENCES TIPO(CODTIPO) ON DELETE CASCADE ON UPDATE CASCADE                                                  
);
--FORNECEDOR={CODFORNECEDOR, NOMEFORNECEDOR, NUMEROCASA, CODRUA,
--CODBAIRRO, CODCEP, CODCIDADE}
CREATE TABLE FORNECEDOR(
	CODFORNECEDOR INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMEFORNECEDOR VARCHAR(80) NOT NULL UNIQUE,
	NUMEROCASA VARCHAR(10) NOT NULL,
	CODRUA INTEGER REFERENCES RUA(CODRUA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODBAIRRO INTEGER REFERENCES BAIRRO(CODBAIRRO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCEP INTEGER REFERENCES CEP(CODCEP) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCIDADE INTEGER REFERENCES CIDADE(CODCIDADE) ON DELETE CASCADE ON UPDATE CASCADE
);
--ITENSTELEFONEFORNECEDOR={CODTELEFONE, CODFORNECEDOR}
CREATE TABLE ITENSTELEFONEFORNECEDOR(
	CODTELEFONE INTEGER REFERENCES TELEFONE(CODTELEFONE) ON DELETE CASCADE ON UPDATE CASCADE,
	CODFORNECEDOR INTEGER REFERENCES FORNECEDOR(CODFORNECEDOR) ON DELETE CASCADE ON UPDATE CASCADE
);
--COMPRAPRODUTO = {CODCOMPRA, DATACOMPRA, CODFORNECEDOR, CODFUNCIONARIO}
CREATE TABLE COMPRAPRODUTO(
	CODCOMPRA INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATACOMPRA DATE NOT NULL,
	CODFORNECEDOR_FK INTEGER REFERENCES FORNECEDOR(CODFORNECEDOR),
	CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(CODFUNCIONARIOS) 
);
-- ITENSCOMPRAPRODUTO = {CODCOMPRA, CODPRODUTO, QUANTIDADE, VALORC}
CREATE TABLE ITENSCOMPRAPRODUTO(
	CODCOMPRA_FK INTEGER REFERENCES COMPRAPRODUTO(CODCOMPRA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODPRODUTO_FK INTEGER REFERENCES PRODUTO(CODPRODUTO) ON DELETE CASCADE ON UPDATE CASCADE,
	QUANTIDADE NUMERIC(10,2) NOT NULL,
	VALORC NUMERIC(10,2) NOT NULL
);
CREATE TABLE SITUACAO(
	CODSITUACAO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMESITUACAO VARCHAR(80) NOT NULL UNIQUE
);
--PARCELACOMPRA = {CODPARCELACOMPRA, DATAVENCIMENTO, VALOR, CODSITUACAO, CODCOMPRA}
CREATE TABLE PARCELACOMPRA(
	CODPARCELACOMPRA INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATAVENCIMENTO DATE NOT NULL,
	VALORP NUMERIC(10,2) NOT NULL,
	CODSITUACAO_FK INTEGER REFERENCES SITUACAO(CODSITUACAO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODCOMPRA_FK INTEGER REFERENCES COMPRAPRODUTO(CODCOMPRA) ON DELETE CASCADE ON UPDATE CASCADE
);
--VENDAPRODUTO = {CODVENDA, DATAVENDA, CODCLIENTE, CODFUNCIONARIO}
CREATE TABLE VENDAPRODUTO(
	CODVENDA INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATAVENDA DATE NOT NULL,
	CODCLIENTE_FK INTEGER REFERENCES CLIENTE(CODCLIENTE),
	CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(CODFUNCIONARIOS) 
);
--ITENSVENDAPRODUTO = {CODVENDA,CODPRODUTO, QUANTIDADE, VALOR}
CREATE TABLE ITENSVENDAPRODUTO(
	CODVENDA_FK INTEGER REFERENCES VENDAPRODUTO(CODVENDA) ON DELETE CASCADE ON UPDATE CASCADE,
	CODPRODUTO_FK INTEGER REFERENCES  PRODUTO(CODPRODUTO) ON DELETE CASCADE ON UPDATE CASCADE,
	QUANTIDADE NUMERIC(10,2) NOT NULL
);

--PARCELAVENDA={CODPARCELA, DATAVENCIMENTO, VALOR, CODSITUACAO, CODVENDA}
CREATE TABLE PARCELAVENDA(
	CODPARCELA INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATAVENCIMENTO DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	CODSITUACAO_FK INTEGER REFERENCES SITUACAO(CODSITUACAO) ON DELETE CASCADE ON UPDATE CASCADE,
	CODVENDA_FK INTEGER REFERENCES VENDAPRODUTO(CODVENDA) ON DELETE CASCADE ON UPDATE CASCADE
);

--IMAGENS={CODIMAGENS, IMAGEM, DESCRICAO, CODPRODUTO}
CREATE TABLE IMAGENS(
	CODIMAGENS INTEGER IDENTITY(1,1) PRIMARY KEY,
	IMAGEM VARBINARY(MAX),
	DESCRICAO VARCHAR(255),
	CODPRODUTO_FK INTEGER REFERENCES PRODUTO(CODPRODUTO) ON DELETE CASCADE ON UPDATE CASCADE
);